### ISSUE TITLE
Error Updating Sensor

### ISSUE THREAD

**Issue by matthewpaul-us** [wxt9861/ynab#11]
home assistant: core-2021.7.3
ynab: v0.1.9

The sensor seemed to work (maybe) the first time, but it has pretty consistently failed after that.

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/ynab/__init__.py:107 
Integration: ynab (documentation, issues) 
First occurred: 01:43:30 (3 occurrences) 
Last logged: 01:53:30

Update for sensor.ynab fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8e6ef3a0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.youneedabudget.com', port=443): Max retries exceeded with url: /v1/budgets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e6ef3a0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 401, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 609, in async_device_update
    raise exc
  File "/config/custom_components/ynab/sensor.py", line 31, in async_update
    await self.hass.data[DOMAIN_DATA]["client"].update_data()
  File "/config/custom_components/ynab/__init__.py", line 107, in update_data
    self.all_budgets = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ynab_sdk/api/budgets.py", line 12, in get_budgets
    response = self.client.get("/budgets")
  File "/usr/local/lib/python3.9/site-packages/ynab_sdk/utils/clients/default_client.py", line 14, in get
    response = requests.get(url, headers=self.headers)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.youneedabudget.com', port=443): Max retries exceeded with url: /v1/budgets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e6ef3a0>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by wxt9861** [comment]
Is this still an issue? Looking at the error, looks like your system could not connect to api.youneedabudget.com.

**Comment by matthewpaul-us** [comment]
I just took a look through my logs and haven't had an issue with this within the past week, so it looks like it resolved itself. I'll go ahead and close it.

I missed that there was a connection issue in the logs. Thanks for pointing that out! If I have another issue, I should be able to open a better ticket in the future.

Also, thanks so much for the integration! It has helped quite a bit with keeping up with my budget 😄
