### ISSUE TITLE
Claude AI Magically Fixed My YNAB Integration and I Wanted to Share In Case It's Helpful Or To Find Out If I Have Made A Poor Decision

### ISSUE THREAD

**Issue by luther84** [wxt9861/ynab#34]
Title is accurate, sharing in case it helps someone else.... or to give people a chance to tell me how badly Claude is screwing me over.

So I finally remembered that this integration existed and decided to add it to my homeassistant instance a couple of days ago. This is such a neat integration and it will enable some cool automations that will greatly boost my Partner Approval Factor. I installed it via the HACS following the instructions and saw the following error in logs after restarting.

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:727
integration: Sensor (documentation, issues)
First occurred: 3:02:59 PM (1 occurrences)
Last logged: 3:02:59 PM
ynab: Error on device update!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 727, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/ynab/sensor.py", line 32, in async_update
    await self.hass.data[DOMAIN_DATA]["client"].update_data()
  File "/config/custom_components/ynab/__init__.py", line 123, in update_data
    self.all_budgets = await self.hass.async_add_executor_job(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ynab_sdk/api/budgets.py", line 13, in get_budgets
    return BudgetSummaryResponse.from_dict(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_summary.py", line 102, in from_dict
    data = Data.from_dict(obj.get("data"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_summary.py", line 91, in from_dict
    budgets = parsers.from_list(Budget.from_dict, obj.get("budgets"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ynab_sdk/utils/parsers.py", line 47, in from_list
    return [f(y) for y in x]
            ^^^^
  File "/usr/local/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_summary.py", line 72, in from_dict
    currency_format = CurrencyFormat.from_dict(obj.get("currency_format"))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ynab_sdk/api/models/responses/budget_summary.py", line 21, in from_dict
    assert isinstance(obj, dict)
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

I thought I had messed up the configuration.yml so I tried cutting it down to the minimum, changing things etc.. No dice. I checked this repo's issues and didn't see anything, checked the original ynab-sdk repo and also didn't see anything there.

I got claude involved and after a very long back and forth I ended up with this:
```quote
Here's what you can do:

In your custom component directory (/config/custom_components/ynab/), create a new file called ynab_sdk_patch.py.

Add the following code to ynab_sdk_patch.py:
```
```python
from ynab_sdk.api.models.responses.budget_summary import CurrencyFormat, Budget
from ynab_sdk.utils import parsers

def patched_currency_format_from_dict(obj):
    if obj is None or not isinstance(obj, dict):
        print(f"Warning: currency_format is not a dict. Received: {obj}")
        return CurrencyFormat("", "", 0, "", False, "", "", False)
    
    iso_code = parsers.from_str(obj.get("iso_code", ""))
    example_format = parsers.from_str(obj.get("example_format", ""))
    decimal_digits = parsers.from_int(obj.get("decimal_digits", 0))
    decimal_separator = parsers.from_str(obj.get("decimal_separator", ""))
    symbol_first = parsers.from_bool(obj.get("symbol_first", False))
    group_separator = parsers.from_str(obj.get("group_separator", ""))
    currency_symbol = parsers.from_str(obj.get("currency_symbol", ""))
    display_symbol = parsers.from_bool(obj.get("display_symbol", False))
    
    return CurrencyFormat(
        iso_code,
        example_format,
        decimal_digits,
        decimal_separator,
        symbol_first,
        group_separator,
        currency_symbol,
        display_symbol,
    )

def patched_budget_from_dict(obj):
    assert isinstance(obj, dict)
    budget_id = parsers.from_str(obj.get("id"))
    name = parsers.from_str(obj.get("name"))
    last_modified_on = parsers.from_datetime(obj.get("last_modified_on"))
    first_month = parsers.from_str(obj.get("first_month"))
    last_month = parsers.from_str(obj.get("last_month"))
    date_format = obj.get("date_format")
    currency_format = patched_currency_format_from_dict(obj.get("currency_format"))
    return Budget(
        budget_id,
        name,
        last_modified_on,
        first_month,
        last_month,
        date_format,
        currency_format,
    )

# Patch the original methods
CurrencyFormat.from_dict = staticmethod(patched_currency_format_from_dict)
Budget.from_dict = staticmethod(patched_budget_from_dict)
```
```quote
In your __init__.py file, add the following import at the top:
```
```python
from .ynab_sdk_patch import *
```

I don't know much about python development but this didn't look like it was going to steal my data or permanently break my homeassistant so I copy pasted this all in where Claude suggested and my ynab integration is working now. Does anyone know what I did and whether this was a good idea? Is it just working for everyone else, did I bark up a wrong tree? Will AI take all our jobs and do pigs have wings?

**Comment by munkyhanger82** [comment]
Thanks for this, I'm having the same issues as you describe so appreciate sharing a resolution. I've followed your advice to the letter, copying the code verbatim to the files detailed, and unfortunately it hasn't resolved the original sensor error. Am I missing something? Thanks

**Comment by wxt9861** [comment]
The issue as described in the OP is not with the custom component itself, but the ynab_sdk used by the component. The solution provided is at your own risk. 

If you want help, open a separate issue and provide details and logs about your configuration.
